[book]
authors = ["Translational Sensory & Circadian Neuroscience Unit (MPS/TUM/TUMCREATE)"]
language = "en"
multilingual = false
src = "src"
title = "Translational Sensory & Circadian Neuroscience Unit (MPS/TUM/TUMCREATE) Lab Handbook"

[output.html]
additional-css = ["custom.css"]
